package edu.temple.howcanihelpapp.Firebase.DatabaseItems;

import java.util.Date;

import edu.temple.howcanihelpapp.Firebase.AuthenticationHelper;
import edu.temple.howcanihelpapp.Firebase.AuthenticationHelperImpl;

public class HelpListingBuilder {
    protected HelpListing helpListing;

    public HelpListingBuilder() throws AuthenticationHelper.UnauthenticatedUserException {
        this.helpListing = new HelpListing();
        // Set the expected values.
        {
            // The time posted is generated here, but it should probably be generated by the
            // backend in the future.
            this.helpListing.timePostedMs = new Date().getTime();
            // The uid is set to the currently authenticated user's uid.
            this.helpListing.uid = AuthenticationHelperImpl.getInstance().getUser().getUid();
        }

        // Set the default values.
        {
            this.helpListing.isRequest = false;
            this.helpListing.isUrgent = false;
            this.helpListing.canRelocate = false;
        }
    }

    public HelpListingBuilder(HelpListing helpListing) {
        this.helpListing = helpListing;
    }

    public HelpListingBuilder setAsRequest() {
        this.helpListing.isRequest = true;
        return this;
    }

    public HelpListingBuilder setAsDonor() {
        this.helpListing.isRequest = false;
        return this;
    }

    public HelpListingBuilder setTitle(String title) {
        this.helpListing.title = title;
        return this;
    }

    public HelpListingBuilder setDescription(String description) {
        this.helpListing.description = description;
        return this;
    }

    public HelpListingBuilder setLocation(HelpListing.Location location) {
        this.helpListing.location = location;
        return this;
    }

    public HelpListingBuilder setIsUrgent(boolean isUrgent) {
        this.helpListing.isUrgent = isUrgent;
        return this;
    }

    public HelpListingBuilder setCanRelocate(boolean canRelocate) {
        this.helpListing.canRelocate = canRelocate;
        return this;
    }

    public HelpListing getHelpListing() {
        return this.helpListing;
    }
}
